#!/usr/bin/env pwsh
# Forge Workflow Commit-Msg Hook
# Generated by Forge Terminal Workflow Architect
# Validates commit message format: type: description
# Bypass with: git commit --no-verify

$ErrorActionPreference = "Continue"
$commitMsgFile = $args[0]
if (-not $commitMsgFile -or -not (Test-Path $commitMsgFile)) {
    Write-Host "commit-msg hook: no message file provided" -ForegroundColor Yellow
    exit 0
}

$commitMessage = Get-Content $commitMsgFile -Raw -ErrorAction SilentlyContinue
if (-not $commitMessage) { exit 0 }

# Extract the first line (subject) — ignore comments and blank lines
$subjectLine = ($commitMessage -split "`n" | Where-Object { $_ -and $_ -notmatch '^#' } | Select-Object -First 1).Trim()
if (-not $subjectLine) { exit 0 }

# Allow merge commits and revert commits through without format check
if ($subjectLine -match '^(Merge |Revert )') { exit 0 }

# Validate format: type: description
$validTypes = @("feat", "fix", "chore", "docs", "test", "refactor", "perf")
$formatPattern = '^(feat|fix|chore|docs|test|refactor|perf):\s+.+'
if ($subjectLine -notmatch $formatPattern) {
    Write-Host "" 
    Write-Host "COMMIT-MSG VIOLATION:" -ForegroundColor Red
    Write-Host "  Message: '$subjectLine'" -ForegroundColor Red
    Write-Host "  Expected format: type: description" -ForegroundColor Red
    Write-Host "  Valid types: $($validTypes -join ', ')" -ForegroundColor Yellow
    Write-Host "  Example: feat: add user authentication flow" -ForegroundColor Green
    Write-Host "" 
    Write-Host "Commit blocked. Fix the message format or use --no-verify to bypass." -ForegroundColor Red
    exit 1
}

# Check for Co-authored-by trailer (warning only, not blocking)
if ($commitMessage -notmatch 'Co-authored-by:') {
    Write-Host "COMMIT-MSG WARNING: Missing Co-authored-by trailer" -ForegroundColor Yellow
}

Write-Host "Commit message format valid" -ForegroundColor Green
exit 0
