#!/usr/bin/env pwsh
# Forge Workflow Pre-Push Hook
# Generated by Forge Terminal Workflow Architect
# Runs build + test suite before allowing push. Ensures broken code never reaches remote.
# Bypass with: git push --no-verify

$ErrorActionPreference = "Continue"
$failures = @()

Write-Host "Running pre-push checks..." -ForegroundColor Cyan

# ── Go Build + Test ─────────────────────────────────────────────────────
if (Test-Path "go.mod") {
    # Projects using a-h/templ generate Go source from .templ files that are
    # gitignored (*_templ.go); regenerate them first so a clean build does not fail.
    # Guarded on the templ tool directive so this is a no-op in non-templ projects.
    if (Select-String -Path go.mod -Pattern "tool github.com/a-h/templ" -Quiet) {
        Write-Host "  [Go] Generating templ files..." -ForegroundColor Cyan
        go tool templ generate *> $null
    }
    Write-Host "  [Go] Building..." -ForegroundColor Cyan
    # Build every package, not a single hardcoded entrypoint, so this hook stays
    # correct regardless of the project's cmd/ layout.
    $buildOutput = go build ./... 2>&1
    if ($LASTEXITCODE -ne 0) {
        $failures += "GO BUILD: go build ./... failed"
        Write-Host "  [Go] Build FAILED" -ForegroundColor Red
        Write-Host $buildOutput -ForegroundColor Red
    } else {
        Write-Host "  [Go] Build passed" -ForegroundColor Green
    }

    Write-Host "  [Go] Testing..." -ForegroundColor Cyan
    $testOutput = go test ./... 2>&1
    if ($LASTEXITCODE -ne 0) {
        $failures += "GO TEST: go test ./... failed"
        Write-Host "  [Go] Tests FAILED" -ForegroundColor Red
        Write-Host $testOutput -ForegroundColor Red
    } else {
        Write-Host "  [Go] Tests passed" -ForegroundColor Green
    }
}

# ── Frontend Build + Test ───────────────────────────────────────────────
if (Test-Path "frontend/package.json") {
    Write-Host "  [Frontend] Testing..." -ForegroundColor Cyan
    Push-Location frontend
    $vitestOutput = npx vitest run 2>&1
    if ($LASTEXITCODE -ne 0) {
        $failures += "FRONTEND TEST: npx vitest run failed"
        Write-Host "  [Frontend] Tests FAILED" -ForegroundColor Red
        Write-Host $vitestOutput -ForegroundColor Red
    } else {
        Write-Host "  [Frontend] Tests passed" -ForegroundColor Green
    }
    Pop-Location
}

# ── Report ──────────────────────────────────────────────────────────────
if ($failures.Count -gt 0) {
    Write-Host ""
    Write-Host "PRE-PUSH FAILURES (blocking):" -ForegroundColor Red
    foreach ($f in $failures) { Write-Host "  * $f" -ForegroundColor Red }
    Write-Host "Push blocked. Fix failures or use --no-verify to bypass." -ForegroundColor Red
    exit 1
}

Write-Host "Pre-push checks passed" -ForegroundColor Green
exit 0
