#!/usr/bin/env pwsh
# Forge Workflow Pre-Commit Hook (Enhanced)
# Generated by Forge Terminal Workflow Architect
# Enforces: main branch block, test file gate, CHANGELOG, naming, branch naming.
# Bypass with: git commit --no-verify (bypasses are logged)

$ErrorActionPreference = "Continue"
$violations = @()
$warnings = @()

# ── MAIN BRANCH BLOCK (Gate 2) ──────────────────────────────────────────
# Commits directly to main are forbidden. All work must happen on feature branches.
$currentBranch = git branch --show-current 2>$null
if ($currentBranch -eq "main" -or $currentBranch -eq "master") {
    $violations += "MAIN BRANCH: Cannot commit directly to main — create a feature branch first"
}

# Branch Naming Check
$validBranchPattern = "^(main|master|develop|feature/.+|fix/.+|chore/.+|docs/.+|hotfix/.+|release/.+)$"
if ($currentBranch -and $currentBranch -notmatch $validBranchPattern) {
    $violations += "BRANCH: '$currentBranch' does not match naming convention"
}

# Get Staged Files
$stagedFiles = git diff --cached --name-only --diff-filter=ACM 2>$null
if (-not $stagedFiles) { exit 0 }

$sourceExtensions = @(".go", ".js", ".jsx", ".ts", ".tsx", ".py", ".rs", ".java", ".cs")
$sourceFiles = $stagedFiles | Where-Object {
    $extension = [System.IO.Path]::GetExtension($_)
    $sourceExtensions -contains $extension
}

# Naming Convention Check
$allowedSingleLetters = @('i', 'j', 'k', 'w', 'r', '_')
foreach ($filePath in $sourceFiles) {
    if (-not (Test-Path $filePath)) { continue }
    $lineNumber = 0
    foreach ($line in (Get-Content $filePath -ErrorAction SilentlyContinue)) {
        $lineNumber++
        if ($line -match '^\s*(var|let|const|)\s*([a-z])\s*[:=]') {
            $varName = $Matches[2]
            if ($varName -and $varName.Length -eq 1 -and $allowedSingleLetters -notcontains $varName) {
                $warnings += "NAMING: ${filePath}:${lineNumber} - Single-letter variable '$varName'"
            }
        }
    }
}

# ── TEST FILE GATE (Gate 4) ─────────────────────────────────────────────
# Every new source file must have a corresponding test file — staged or found
# anywhere in the repo (test projects/dirs are common). Conventions are
# language-specific: Go (_test.go), JS/TS (.test/.spec), Python (test_ prefix
# or _test suffix), Rust (_test.rs or inline #[cfg(test)]), C# (Tests/Test
# suffix), Java (Test/Tests/IT). Build output directories are excluded.
$buildOutputDirs = @("cmd/forge/web/", "frontend/dist/", "bin/")
$newSourceFiles = git diff --cached --name-only --diff-filter=A 2>$null | Where-Object {
    $extension = [System.IO.Path]::GetExtension($_)
    if (-not ($sourceExtensions -contains $extension)) { return $false }
    foreach ($buildDir in $buildOutputDirs) {
        if ($_ -like "$buildDir*") { return $false }
    }
    return $true
}
# Recognise a path that is itself a test file (so a new test file isn't flagged).
$isTestFile = { param($f)
    $name = [System.IO.Path]::GetFileName($f)
    if ($name -match '(_test\.go|\.test\.(js|jsx|ts|tsx)|\.spec\.(js|jsx|ts|tsx)|_test\.py|_test\.rs)$') { return $true }
    if ($name -like 'test_*.py') { return $true }
    if ($name -match '(Tests|Test)\.cs$') { return $true }
    if ($name -match '(Test|Tests|IT)\.java$') { return $true }
    return $false
}
# Candidate test FILE NAMES for a source leaf, by language.
$testCandidates = { param($leaf, $ext)
    switch ($ext) {
        '.go'   { return @("${leaf}_test.go") }
        '.js'   { return @("${leaf}.test.js", "${leaf}.spec.js") }
        '.jsx'  { return @("${leaf}.test.jsx", "${leaf}.spec.jsx") }
        '.ts'   { return @("${leaf}.test.ts", "${leaf}.spec.ts") }
        '.tsx'  { return @("${leaf}.test.tsx", "${leaf}.spec.tsx") }
        '.py'   { return @("test_${leaf}.py", "${leaf}_test.py") }
        '.rs'   { return @("${leaf}_test.rs") }
        '.cs'   { return @("${leaf}Tests.cs", "${leaf}Test.cs", "${leaf}.Tests.cs", "${leaf}.Test.cs") }
        '.java' { return @("${leaf}Test.java", "${leaf}Tests.java", "${leaf}IT.java") }
        default { return @() }
    }
}
foreach ($newFile in $newSourceFiles) {
    if (& $isTestFile $newFile) { continue }
    $extension = [System.IO.Path]::GetExtension($newFile)
    $leaf = [System.IO.Path]::GetFileNameWithoutExtension($newFile)
    $hasTest = $false
    # Rust commonly keeps unit tests inline in the same file via #[cfg(test)].
    if ($extension -eq '.rs' -and (Test-Path $newFile) -and (Select-String -Path $newFile -Pattern '#\[cfg\(test\)\]' -Quiet -ErrorAction SilentlyContinue)) {
        $hasTest = $true
    }
    if (-not $hasTest) {
        foreach ($cand in (& $testCandidates $leaf $extension)) {
            if ($stagedFiles | Where-Object { [System.IO.Path]::GetFileName($_) -eq $cand }) { $hasTest = $true; break }
            if (Get-ChildItem -Path . -Recurse -File -Filter $cand -ErrorAction SilentlyContinue | Select-Object -First 1) { $hasTest = $true; break }
        }
    }
    if (-not $hasTest) {
        $violations += "TEST FILE: New source file '$newFile' has no corresponding test file"
    }
}

# ── CHANGELOG CHECK (Gate 7 — upgraded to violation) ────────────────────
# Source files changed but CHANGELOG.md not updated = blocking violation.
# Version-bump commits (only build artifacts / config staged) are exempt
# because the release script manages CHANGELOG in the same commit.
$versionOnlyPattern = '^(internal/updater/updater\.go|frontend/package\.json|frontend/src/config/tourSteps\.js|cmd/forge/web/|resource\.syso|version\.json|go\.sum)$'
$isVersionBump = $true
foreach ($staged in $stagedFiles) {
    if ($staged -notmatch $versionOnlyPattern) { $isVersionBump = $false; break }
}
$hasSourceChanges = ($sourceFiles | Measure-Object).Count -gt 0
$changelogUpdated = $stagedFiles | Where-Object { $_ -match "CHANGELOG\.md$" }
if ($hasSourceChanges -and -not $changelogUpdated -and -not $isVersionBump) {
    $violations += "CHANGELOG: Source files changed but CHANGELOG.md was not updated"
}

# Report Results
if ($violations.Count -gt 0) {
    Write-Host ""
    Write-Host "PRE-COMMIT VIOLATIONS (blocking):" -ForegroundColor Red
    foreach ($v in $violations) { Write-Host "  * $v" -ForegroundColor Red }
}
if ($warnings.Count -gt 0) {
    Write-Host ""
    Write-Host "PRE-COMMIT WARNINGS (non-blocking):" -ForegroundColor Yellow
    foreach ($w in $warnings) { Write-Host "  * $w" -ForegroundColor Yellow }
}
if ($violations.Count -eq 0 -and $warnings.Count -eq 0) {
    Write-Host "Pre-commit checks passed" -ForegroundColor Green
}

if ($violations.Count -gt 0) {
    Write-Host "Commit blocked. Fix violations or use --no-verify to bypass." -ForegroundColor Red
    exit 1
}
exit 0
